#!/usr/bin/env python3

from sys import argv
from math import isqrt


def open_read_file(file_name):
""" Read from file and convert to a list of integers """
with open(file_name, "r", encoding="utf-8") as file:
lines = file.readlines()
return [int(line) for line in lines]


def find_factors(n):
""" Find and print factors of n """
for i in range(2, isqrt(n) + 1):
while n % i == 0:
print("{}={}*{}".format(n, n // i, i))
n //= i
if n > 1:
print("{}=1*{}".format(n, n))


if len(argv) == 2:
numbers = open_read_file(argv[1])
for number in numbers:
find_factors(number)
